sequence_denoising:
  _target_: proteinworkshop.tasks.sequence_denoising.SequenceNoiseTransform
  corruption_rate: 0.5 # Fraction of residues to corrupt
  corruption_strategy: "both" # Whether to 'mutate' or 'mask'
  corruption_target: "3Di"
