_target_: topotein.features.factory.TopoteinFeaturiser
representation: CA
scalar_node_features:
  - amino_acid_one_hot
  - sequence_positional_encoding
  - alpha
  - kappa
  - dihedrals
#  - secondary_structure_one_hot
vector_node_features: []
edge_types:
  - knn_16
scalar_edge_features:
  - edge_distance
#  - node_features
# - sequence_distance
vector_edge_features: []
sse_types:
  - H
  - E
  - C
scalar_sse_features:
  - sse_one_hot
  - sse_size
  - sse_vector_norms
  - sse_variance_wrt_localized_frame
#  - node_features
vector_sse_features: []
neighborhoods: []
directed_edges: False
pure_torch: True

