_target_: topotein.features.factory.TopoteinFeaturiser
representation: CA
scalar_node_features:
  - amino_acid_one_hot
  - sequence_positional_encoding
  - alpha
  - kappa
  - dihedrals
#  - secondary_structure_one_hot
vector_node_features: []
edge_types:
  - knn_16
scalar_edge_features:
  - edge_distance
#  - rbf
#  - node_features
# - sequence_distance
vector_edge_features: []
sse_types:
  - H
  - E
  - C
scalar_sse_features:
  - sse_one_hot
  - sse_size
  - se_pos_encoding
  - consecutive_angle
  - torsional_angle
  - eigenvalues
#  - sse_vector_norms
  - std_wrt_localized_frame
#  - node_features
vector_sse_features: []

scalar_pr_features:
  - aa_freq
  - aa_std
  - sse_freq
  - sse_std
  - sse_size_mean
  - sse_size_std
  - pr_size
  - gyration_r
  - contact_density_and_order
  - eigenvalues
#  - std_wrt_localized_frame

vector_pr_features: []
neighborhoods: []
directed_edges: False
pure_torch: True

