program: /home/zw471/PycharmProjects/Topotein/ProteinWorkshop/proteinworkshop/train.py
method: grid
name: topotein_baseline_go
metric: # Does not matter, as we are using sweep to run the experiment.
  goal: minimize
  name: val/loss/total

parameters:
  task:
    values: [multiclass_graph_classification]

  dataset:
    values: [go-mf, go-bp, go-cc]

  encoder:
    values: [tcpnet]

  optimiser.optimizer.lr:
    values: [0.0001]

  features:
    values: [ca_bb_sse]

  scheduler:
    values: [plateau]

  extras.enforce_tags:
    values: [False]

  +aux_task:
    values: [none]

  trainer.max_epochs:
    value: 150

command:
  - ${env}
  - HYDRA_FULL_ERROR=1
  - WANDB_START_METHOD=thread
  - python
  - ${program}
  - ${args_no_hyphens}
