_target_: topotein.models.graph_encoders.ETNN_original.ETNNModel
features:
  # note: will manually be injected into `/features` via `validate_topotein_config()` of `proteinworkshop/configs/config.py`
  neighborhoods:
    - N2_0 = B0_2.T
    - N1_0 = B0_1.T
    - N0_0_via_1 = A0_1
    - N0_0_via_2 = A0_2

num_layers: 6 # Number of layers in the model
emb_dim: 128
activation: silu # Activation function to use in each GCP layer
pool: sum # Global pooling method to be used

model_cfg:
  in_dim0: ${resolve_feature_config_dim:${features},scalar_node_features,${task},true}
  in_dim1: ${resolve_feature_config_dim:${features},scalar_edge_features,${task},true}
  in_dim2: ${resolve_feature_config_dim:${features},scalar_sse_features,${task},true}
  emb_dim: ${..emb_dim}
  activation: ${..activation}
  num_layers: ${..num_layers}
  pool: ${..pool}
  dropout: 0.1

layer_cfg:
  norm: batch