node_recon:
  _target_: "proteinworkshop.models.decoders.mlp_decoder.MLPDecoder"
  hidden_dim: 
    - ${vq_vae.code_dim} 
    - ${vq_vae.code_dim} 
  dropout: 0.0 # dropout rate
  activations: ["relu", "relu", "none"]
  skip: "concat" # Or sum/False
  out_dim: ${resolve_feature_config_dim:${features},scalar_node_features,${task},true}
  input: "node_embedding_quantized"
